"""Numerical tools for potential energy surface exploration."""

from .calculus import (
    PESPoint,
    central_difference_gradient,
    central_difference_hessian,
    curvature,
    evaluate_pes,
    force,
    gradient,
    hessian,
)
from .benchmarks import (
    BenchmarkResult,
    OptimizerBenchmarkResult,
    benchmark_optimizer_run,
    benchmark_pes_evaluation,
)
from .classification import (
    StationaryPointType,
    classify_hessian,
    classify_pes_point,
)
from .evf import (
    EVFOptimizer,
    EVFSettings,
    EVFStepResult,
    lowest_mode,
    reaction_coordinate_from_hessian,
)
from .instrumentation import EnergyCallCounter
from .labels import (
    PESLabel,
    export_labels_csv_summary,
    export_labels_jsonl,
    generate_pes_label,
    label_to_dict,
)
from .matrix import (
    add_matrices,
    add_vectors,
    determinant,
    dot,
    has_first_order_saddle,
    identity,
    is_first_order_saddle,
    is_symmetric,
    jacobi_eigendecomposition_symmetric,
    jacobi_eigenvalues_symmetric,
    matmul,
    matvec,
    max_abs_off_diagonal,
    negative_eigenvalue_count,
    norm,
    normalize_vector,
    outer,
    project,
    scale_matrix,
    scale_vector,
    shape,
    solve_linear_system,
    subtract_matrices,
    subtract_vectors,
    trace,
    transpose,
    vector_distance,
    zeros,
)
from .optimizers import (
    OptimizationResult,
    OptimizationStep,
    eigenvector_following_saddle_search,
)
from .physical_models import lennard_jones_cluster_energy
from .surfaces import (
    coupled_quadratic_saddle,
    muller_brown,
    quadratic_first_order_saddle,
    quadratic_minimum,
)
from .topology_models import (
    ElectrophileTopologyParameters,
    benzene_electrophile_starting_points,
    benzene_electrophile_topology_energy,
    default_no_plus_topology_parameters,
    evaluate_topology_stationary_candidates,
)

__all__ = [
    "add_matrices",
    "add_vectors",
    "BenchmarkResult",
    "benzene_electrophile_starting_points",
    "benzene_electrophile_topology_energy",
    "benchmark_optimizer_run",
    "benchmark_pes_evaluation",
    "PESPoint",
    "PESLabel",
    "StationaryPointType",
    "central_difference_gradient",
    "central_difference_hessian",
    "classify_hessian",
    "classify_pes_point",
    "coupled_quadratic_saddle",
    "curvature",
    "default_no_plus_topology_parameters",
    "determinant",
    "dot",
    "ElectrophileTopologyParameters",
    "eigenvector_following_saddle_search",
    "EnergyCallCounter",
    "EVFOptimizer",
    "EVFSettings",
    "EVFStepResult",
    "evaluate_pes",
    "evaluate_topology_stationary_candidates",
    "export_labels_csv_summary",
    "export_labels_jsonl",
    "force",
    "generate_pes_label",
    "gradient",
    "has_first_order_saddle",
    "hessian",
    "identity",
    "is_first_order_saddle",
    "is_symmetric",
    "jacobi_eigendecomposition_symmetric",
    "jacobi_eigenvalues_symmetric",
    "label_to_dict",
    "lennard_jones_cluster_energy",
    "lowest_mode",
    "matmul",
    "matvec",
    "max_abs_off_diagonal",
    "muller_brown",
    "negative_eigenvalue_count",
    "norm",
    "normalize_vector",
    "OptimizerBenchmarkResult",
    "OptimizationResult",
    "OptimizationStep",
    "outer",
    "project",
    "quadratic_first_order_saddle",
    "quadratic_minimum",
    "reaction_coordinate_from_hessian",
    "scale_matrix",
    "scale_vector",
    "shape",
    "solve_linear_system",
    "subtract_matrices",
    "subtract_vectors",
    "trace",
    "transpose",
    "vector_distance",
    "zeros",
]
